linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt

linters-settings:
  errcheck:
    check-blank: true
  misspell:
    locale: US

run:
  timeout: 5m
  skip-dirs:
    - vendor
